version: '3.7'

services: 

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_PASSWORD: admin
      MYSQL-USER: admin
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
